---
title: "Data Transfer and Folder Manipulation"
author: "Kourtney Burger"
date: "2024-10-07"
output: html_document
---
```{r}
library(dplyr)
```

# Make Calibration File
- only run once! 
```{r}
# download deployment details from spreadsheet (https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit?gid=395545420#gid=395545420)

#Read in deployment details and pull required columns to make new dataframe
dd <- read.csv(here::here("R/Spreadsheets & Templates/SAEL Metadata/Deployment Details - NEW DEPLOYMENT TO SAVE.csv"))
calFile <- dd %>%
  select("Drift.", "Array_name..Array.letter...2.digit.version.number_Hydrophone.model.numbers.",
         "ChannelNumber_1","SensorNumber_1..hydrophone.serial.number.", 
         "ChannelNumber_2", "SensorNumber_2...hydrophone.serial.number.")

# Rename columns
calFile <- calFile %>%
  rename(
    DeploymentID = "Drift.",
    HydrophoneArray = "Array_name..Array.letter...2.digit.version.number_Hydrophone.model.numbers.",
    SensorNumber_1 = "ChannelNumber_1",
    SerialNumber_1 = "SensorNumber_1..hydrophone.serial.number.",
    SensorNumber_2 = "ChannelNumber_2",
    SerialNumber_2 = "SensorNumber_2...hydrophone.serial.number."
  )

# Load inventory info
inven <- read.csv(here::here("R/Spreadsheets & Templates/SAEL Metadata/Inventory - Hydrophones.csv"))

# Add hydrophone type, sensitivity, and current info
channel_1 <- inven %>%
  select(Serial.Number, Model, Hydrophone.Sensitivity.dB.re..1V.uPa, Current.mA) %>%
  rename(
    HydrophoneType_1 = Model,
    HydrophoneSensitivity_1 = Hydrophone.Sensitivity.dB.re..1V.uPa,
    Current_mA_1 = Current.mA
  )

channel_2 <- inven %>%
  select(Serial.Number, Model, Hydrophone.Sensitivity.dB.re..1V.uPa, Current.mA) %>%
  rename(
    HydrophoneType_2 = Model,
    HydrophoneSensitivity_2 = Hydrophone.Sensitivity.dB.re..1V.uPa,
    Current_mA_2 = Current.mA
  )

# Perform left joins for SerialNumber_1, SerialNumber_2, and SerialNumber_3
calFile <- calFile %>%
  left_join(channel_1, by = c("SerialNumber_1" = "Serial.Number")) %>%
  left_join(channel_2, by = c("SerialNumber_2" = "Serial.Number"))

# Reorder columns
calFile <- calFile[, c("DeploymentID", "HydrophoneArray", "SensorNumber_1", 
                       "HydrophoneType_1", "SerialNumber_1", "HydrophoneSensitivity_1", 
                       "Current_mA_1", "SensorNumber_2", "HydrophoneType_2", 
                       "SerialNumber_2", "HydrophoneSensitivity_2", "Current_mA_2")]

write.csv(calFile, here::here("R/Spreadsheets & Templates/CalCurCEAS_CalibrationInfo.csv"), row.names = FALSE)
```

# Move files to prep for archive
 - moving GPS data, 
 - moving accelerometer data, log files, and depth data to other folder
 
```{r}
#Read in deployment details
dd <- read.csv(here::here("R/Spreadsheets & Templates/SAEL Metadata/Deployment Details - NEW DEPLOYMENT TO SAVE.csv"))
```

```{r}
#Create file path
dir.create(file.path('E:/CalCurCEAS PACE/'))
dir.create(file.path('E:/CalCurCEAS PACE/metadata'))
```

```{r}
#Move GPS data
for (i in 1:nrow(dd)) {
  dir.create(file.path('E:/CalCurCEAS PACE/metadata', dd$Data_ID[i]))  
  
  # List of current gps files location
  currentGPS <- list.files(paste0('Z:/METADATA/CalCurCEAS_2024/',dd$Data_ID[i],
                                 '/',dd$Data_ID[i],'_GPS'), 
                           pattern = "\\_GPS.csv$", full.names = T)
  
  # Create folder/directory to move the list above to
  dir.create(file.path(paste0('E:/CalCurCEAS PACE/metadata/', dd$Data_ID[i],'/gps')))
  
  newGPS <- file.path(paste0('E:/CalCurCEAS PACE/metadata/', dd$Data_ID[i],'/gps'))

  # Copy list of files to new directory
  file.copy(currentGPS, newGPS)
}  
```

```{r}
# Move other data

# Set up progress bar
pb <- txtProgressBar(min = 0, max = nrow(dd), style = 3, width = 50, char = "=")  

for (i in 1:nrow(dd)) {
  # Accelerometer
    currentAccel <- list.files(paste0('Z:/RECORDINGS/DRIFTERS/CalCurCEAS_2024/RAW/',
                                      dd$Data_ID[i], '/ACCELERATION'),
                               pattern = "\\.accel.csv$", full.names = T)

    # Create folder/directory to move the list above to
    dir.create(file.path(paste0('E://CalCurCEAS PACE/metadata/',
                                dd$Data_ID[i],'/accelerometer')))
    newAccel <- file.path(paste0('E://CalCurCEAS PACE/metadata/',
                                dd$Data_ID[i],'/accelerometer'))
    # Copy list of files to new directory
    file.copy(currentAccel, newAccel)


  # Logs
    currentLogs <- list.files(paste0('Z:/RECORDINGS/DRIFTERS/CalCurCEAS_2024/RAW/',
                                      dd$Data_ID[i], '/LOG'),
                               pattern = "\\.log.xml$", full.names = T)

    # Create folder/directory to move the list above to
    dir.create(file.path(paste0('E://CalCurCEAS PACE/metadata/',
                                dd$Data_ID[i],'/logs')))
    newLogs <- file.path(paste0('E://CalCurCEAS PACE/metadata/',
                                dd$Data_ID[i],'/logs'))
    # Copy list of files to new directory
    file.copy(currentLogs, newLogs)
    
    
  # Depth
    currentDepth <- list.files(paste0('Z:/METADATA/CalCurCEAS_2024/', dd$Data_ID[i], '/', dd$Data_ID[i], '_Depth_Sensus'), pattern = "_Sensus.csv$", full.names = TRUE)

    # Create folder/directory to move the list above to
    dir.create(file.path(paste0('E://CalCurCEAS PACE/metadata/',
                                dd$Data_ID[i],'/depth')))
    newDepth <- file.path(paste0('E://CalCurCEAS PACE/metadata/',
                                dd$Data_ID[i],'/depth'))
    # Copy list of files to new directory
    file.copy(currentDepth, newDepth)
    
  # Sets the progress bar to the current state
  setTxtProgressBar(pb, i)
}
```

 
```{r}
# Audio data - copying manually after data is packaged to save packaging time

```
 
 